### ISSUE TITLE
Best SDR device to reduce interference?

### ISSUE THREAD

**Issue by trs79** [jj1bdx/airspy-fmradion#37]
I have been using airspy-fmradion with a rtl-sdr dongle with great results for FM radio listening, but unfortunately I hear static (I assume due to EMI interference) depending on where I place the device. My laptop seems to be the worst offender. I'm curious if stepping up to an airspy device (R2, mini, HF+) might help with eliminating the static? Do these devices have better shielding?

**Comment by jj1bdx** [comment]
You first need to check out the antenna. It should be placed outside the building for a better listening.
Also, you need to introduce common-mode choke for reducing the common-mode interference. Brian Beezley, K6STI, has written [a comprehensive article](http://www.ham-radio.com/k6sti/balun.htm) of how to build a common-mode choke. His entire website [88-108MHz](http://www.ham-radio.com/k6sti/) is also a comprehensive source of FM listening expertise.

My experience tells me that the device RF shielding and other characteristics between RTL-SDR, Airspy R2/Mini, and Airspy HF+ Dual Port/Discovery are all far more than sufficient if a sufficiently strong RF signal is provided. OTOH, the output sound quality in general may differ a lot due to the A/D converter capabilities.

This issue is not really a support issue for airspy-fmradion so I'll close for now, but I'll keep it here for a future reference.
