### ISSUE TITLE
Resampling efficiency, and why not choosing 32kHz sampling rate

### ISSUE THREAD

**Issue by touil** [jj1bdx/airspy-fmradion#6]
Note that 32ksps is a standard sample rate supported by all sound cards and is sufficient for FM quality (15 kHz bandwidth). It can be obtained by decimating 256ksps by 4 then by 2.

https://github.com/jj1bdx/airspy-fmradion/blob/2cfb75aea169a698b2cf160e0f99e90aa4019682/main.cpp#L788

**Comment by jj1bdx** [comment]
I've chosen 48kHz as the target audio sampling rate because some high-grade audio interface devices only accept 44.1kHz and 48kHz rates, not 32kHz. I also wanted to keep the frequency response flat at least to 16kHz for the broadcast FM reception.
The current (up to v0.6.14) downsampling structure for AM/USB/LSB decoding is to downsample to as close to the 48kHz as possible with the given integer division ratios. There is one exception, though; for 256kHz, I use 64kHz (simple /4), because using /5 and /6 caused some audible clicks to the output, and this causes a wider bandwidth than necessary for AM/USB/LSB.
I'll keep the target rate to 48kHz for the time being. 32kHz is worth being considered and experimented later, though.
